//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\danie\source\repos\AnalizadorSICXE\AnalizadorSICXE\AnalizadorSICXE.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace AnalizadorSICXE {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="AnalizadorSICXEParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
[System.CLSCompliant(false)]
public interface IAnalizadorSICXEListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="AnalizadorSICXEParser.programa"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrograma([NotNull] AnalizadorSICXEParser.ProgramaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnalizadorSICXEParser.programa"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrograma([NotNull] AnalizadorSICXEParser.ProgramaContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnalizadorSICXEParser.inicio"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInicio([NotNull] AnalizadorSICXEParser.InicioContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnalizadorSICXEParser.inicio"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInicio([NotNull] AnalizadorSICXEParser.InicioContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnalizadorSICXEParser.etiqueta"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEtiqueta([NotNull] AnalizadorSICXEParser.EtiquetaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnalizadorSICXEParser.etiqueta"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEtiqueta([NotNull] AnalizadorSICXEParser.EtiquetaContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnalizadorSICXEParser.fin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFin([NotNull] AnalizadorSICXEParser.FinContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnalizadorSICXEParser.fin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFin([NotNull] AnalizadorSICXEParser.FinContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnalizadorSICXEParser.entrada"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEntrada([NotNull] AnalizadorSICXEParser.EntradaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnalizadorSICXEParser.entrada"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEntrada([NotNull] AnalizadorSICXEParser.EntradaContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnalizadorSICXEParser.proposiciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProposiciones([NotNull] AnalizadorSICXEParser.ProposicionesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnalizadorSICXEParser.proposiciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProposiciones([NotNull] AnalizadorSICXEParser.ProposicionesContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnalizadorSICXEParser.proposiciones1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProposiciones1([NotNull] AnalizadorSICXEParser.Proposiciones1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnalizadorSICXEParser.proposiciones1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProposiciones1([NotNull] AnalizadorSICXEParser.Proposiciones1Context context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnalizadorSICXEParser.proposicion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProposicion([NotNull] AnalizadorSICXEParser.ProposicionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnalizadorSICXEParser.proposicion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProposicion([NotNull] AnalizadorSICXEParser.ProposicionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnalizadorSICXEParser.instruccion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruccion([NotNull] AnalizadorSICXEParser.InstruccionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnalizadorSICXEParser.instruccion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruccion([NotNull] AnalizadorSICXEParser.InstruccionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnalizadorSICXEParser.directiva"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDirectiva([NotNull] AnalizadorSICXEParser.DirectivaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnalizadorSICXEParser.directiva"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDirectiva([NotNull] AnalizadorSICXEParser.DirectivaContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnalizadorSICXEParser.tipodirectiva"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTipodirectiva([NotNull] AnalizadorSICXEParser.TipodirectivaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnalizadorSICXEParser.tipodirectiva"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTipodirectiva([NotNull] AnalizadorSICXEParser.TipodirectivaContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnalizadorSICXEParser.base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBase([NotNull] AnalizadorSICXEParser.BaseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnalizadorSICXEParser.base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBase([NotNull] AnalizadorSICXEParser.BaseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnalizadorSICXEParser.opdirectiva"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpdirectiva([NotNull] AnalizadorSICXEParser.OpdirectivaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnalizadorSICXEParser.opdirectiva"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpdirectiva([NotNull] AnalizadorSICXEParser.OpdirectivaContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnalizadorSICXEParser.opinstruccion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpinstruccion([NotNull] AnalizadorSICXEParser.OpinstruccionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnalizadorSICXEParser.opinstruccion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpinstruccion([NotNull] AnalizadorSICXEParser.OpinstruccionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnalizadorSICXEParser.formato"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormato([NotNull] AnalizadorSICXEParser.FormatoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnalizadorSICXEParser.formato"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormato([NotNull] AnalizadorSICXEParser.FormatoContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnalizadorSICXEParser.f1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterF1([NotNull] AnalizadorSICXEParser.F1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnalizadorSICXEParser.f1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitF1([NotNull] AnalizadorSICXEParser.F1Context context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnalizadorSICXEParser.f2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterF2([NotNull] AnalizadorSICXEParser.F2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnalizadorSICXEParser.f2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitF2([NotNull] AnalizadorSICXEParser.F2Context context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnalizadorSICXEParser.f3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterF3([NotNull] AnalizadorSICXEParser.F3Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnalizadorSICXEParser.f3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitF3([NotNull] AnalizadorSICXEParser.F3Context context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnalizadorSICXEParser.f4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterF4([NotNull] AnalizadorSICXEParser.F4Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnalizadorSICXEParser.f4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitF4([NotNull] AnalizadorSICXEParser.F4Context context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnalizadorSICXEParser.simple3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimple3([NotNull] AnalizadorSICXEParser.Simple3Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnalizadorSICXEParser.simple3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimple3([NotNull] AnalizadorSICXEParser.Simple3Context context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnalizadorSICXEParser.indirecto3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndirecto3([NotNull] AnalizadorSICXEParser.Indirecto3Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnalizadorSICXEParser.indirecto3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndirecto3([NotNull] AnalizadorSICXEParser.Indirecto3Context context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnalizadorSICXEParser.inmediato3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInmediato3([NotNull] AnalizadorSICXEParser.Inmediato3Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnalizadorSICXEParser.inmediato3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInmediato3([NotNull] AnalizadorSICXEParser.Inmediato3Context context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnalizadorSICXEParser.subf2a"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubf2a([NotNull] AnalizadorSICXEParser.Subf2aContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnalizadorSICXEParser.subf2a"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubf2a([NotNull] AnalizadorSICXEParser.Subf2aContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnalizadorSICXEParser.subf2b"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubf2b([NotNull] AnalizadorSICXEParser.Subf2bContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnalizadorSICXEParser.subf2b"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubf2b([NotNull] AnalizadorSICXEParser.Subf2bContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnalizadorSICXEParser.subf2c"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubf2c([NotNull] AnalizadorSICXEParser.Subf2cContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnalizadorSICXEParser.subf2c"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubf2c([NotNull] AnalizadorSICXEParser.Subf2cContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnalizadorSICXEParser.subf2d"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubf2d([NotNull] AnalizadorSICXEParser.Subf2dContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnalizadorSICXEParser.subf2d"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubf2d([NotNull] AnalizadorSICXEParser.Subf2dContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnalizadorSICXEParser.codop1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCodop1([NotNull] AnalizadorSICXEParser.Codop1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnalizadorSICXEParser.codop1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCodop1([NotNull] AnalizadorSICXEParser.Codop1Context context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnalizadorSICXEParser.codop2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCodop2([NotNull] AnalizadorSICXEParser.Codop2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnalizadorSICXEParser.codop2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCodop2([NotNull] AnalizadorSICXEParser.Codop2Context context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnalizadorSICXEParser.codop3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCodop3([NotNull] AnalizadorSICXEParser.Codop3Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnalizadorSICXEParser.codop3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCodop3([NotNull] AnalizadorSICXEParser.Codop3Context context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="AnalizadorSICXEParser.reg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReg([NotNull] AnalizadorSICXEParser.RegContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AnalizadorSICXEParser.reg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReg([NotNull] AnalizadorSICXEParser.RegContext context);
}
} // namespace AnalizadorSICXE
