//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\danie\source\repos\AnalizadorSICXE\AnalizadorSICXE\AnalizadorSICXE.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace AnalizadorSICXE {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="AnalizadorSICXEParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
[System.CLSCompliant(false)]
public interface IAnalizadorSICXEVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorSICXEParser.programa"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrograma([NotNull] AnalizadorSICXEParser.ProgramaContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorSICXEParser.inicio"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInicio([NotNull] AnalizadorSICXEParser.InicioContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorSICXEParser.etiqueta"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEtiqueta([NotNull] AnalizadorSICXEParser.EtiquetaContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorSICXEParser.fin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFin([NotNull] AnalizadorSICXEParser.FinContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorSICXEParser.entrada"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntrada([NotNull] AnalizadorSICXEParser.EntradaContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorSICXEParser.proposiciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProposiciones([NotNull] AnalizadorSICXEParser.ProposicionesContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorSICXEParser.proposiciones1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProposiciones1([NotNull] AnalizadorSICXEParser.Proposiciones1Context context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorSICXEParser.proposicion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProposicion([NotNull] AnalizadorSICXEParser.ProposicionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorSICXEParser.instruccion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruccion([NotNull] AnalizadorSICXEParser.InstruccionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorSICXEParser.directiva"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDirectiva([NotNull] AnalizadorSICXEParser.DirectivaContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorSICXEParser.tipodirectiva"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTipodirectiva([NotNull] AnalizadorSICXEParser.TipodirectivaContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorSICXEParser.base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBase([NotNull] AnalizadorSICXEParser.BaseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorSICXEParser.opdirectiva"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpdirectiva([NotNull] AnalizadorSICXEParser.OpdirectivaContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorSICXEParser.opinstruccion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpinstruccion([NotNull] AnalizadorSICXEParser.OpinstruccionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorSICXEParser.formato"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormato([NotNull] AnalizadorSICXEParser.FormatoContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorSICXEParser.f1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitF1([NotNull] AnalizadorSICXEParser.F1Context context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorSICXEParser.f2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitF2([NotNull] AnalizadorSICXEParser.F2Context context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorSICXEParser.f3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitF3([NotNull] AnalizadorSICXEParser.F3Context context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorSICXEParser.f4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitF4([NotNull] AnalizadorSICXEParser.F4Context context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorSICXEParser.simple3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple3([NotNull] AnalizadorSICXEParser.Simple3Context context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorSICXEParser.indirecto3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndirecto3([NotNull] AnalizadorSICXEParser.Indirecto3Context context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorSICXEParser.inmediato3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInmediato3([NotNull] AnalizadorSICXEParser.Inmediato3Context context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorSICXEParser.subf2a"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubf2a([NotNull] AnalizadorSICXEParser.Subf2aContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorSICXEParser.subf2b"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubf2b([NotNull] AnalizadorSICXEParser.Subf2bContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorSICXEParser.subf2c"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubf2c([NotNull] AnalizadorSICXEParser.Subf2cContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorSICXEParser.subf2d"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubf2d([NotNull] AnalizadorSICXEParser.Subf2dContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorSICXEParser.codop1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCodop1([NotNull] AnalizadorSICXEParser.Codop1Context context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorSICXEParser.codop2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCodop2([NotNull] AnalizadorSICXEParser.Codop2Context context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorSICXEParser.codop3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCodop3([NotNull] AnalizadorSICXEParser.Codop3Context context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorSICXEParser.reg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReg([NotNull] AnalizadorSICXEParser.RegContext context);
}
} // namespace AnalizadorSICXE
