//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\alfre\source\repos\Prueba300\GrammarSICXE.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Example.Generated {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="GrammarSICXEParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
[System.CLSCompliant(false)]
public interface IGrammarSICXEVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.programa"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrograma([NotNull] GrammarSICXEParser.ProgramaContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.inicio"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInicio([NotNull] GrammarSICXEParser.InicioContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.etiqueta"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEtiqueta([NotNull] GrammarSICXEParser.EtiquetaContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.fin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFin([NotNull] GrammarSICXEParser.FinContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.entrada"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntrada([NotNull] GrammarSICXEParser.EntradaContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.proposiciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProposiciones([NotNull] GrammarSICXEParser.ProposicionesContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.proposiciones1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProposiciones1([NotNull] GrammarSICXEParser.Proposiciones1Context context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.proposicion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProposicion([NotNull] GrammarSICXEParser.ProposicionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.instruccion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruccion([NotNull] GrammarSICXEParser.InstruccionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.directiva"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDirectiva([NotNull] GrammarSICXEParser.DirectivaContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.direxref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDirexref([NotNull] GrammarSICXEParser.DirexrefContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.direxdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDirexdef([NotNull] GrammarSICXEParser.DirexdefContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.tipodirectiva"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTipodirectiva([NotNull] GrammarSICXEParser.TipodirectivaContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBase([NotNull] GrammarSICXEParser.BaseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.opdirectiva"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpdirectiva([NotNull] GrammarSICXEParser.OpdirectivaContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.opinstruccion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpinstruccion([NotNull] GrammarSICXEParser.OpinstruccionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.formato"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormato([NotNull] GrammarSICXEParser.FormatoContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.f1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitF1([NotNull] GrammarSICXEParser.F1Context context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.f2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitF2([NotNull] GrammarSICXEParser.F2Context context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.f3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitF3([NotNull] GrammarSICXEParser.F3Context context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.f4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitF4([NotNull] GrammarSICXEParser.F4Context context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.simple3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple3([NotNull] GrammarSICXEParser.Simple3Context context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.indirecto3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndirecto3([NotNull] GrammarSICXEParser.Indirecto3Context context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.inmediato3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInmediato3([NotNull] GrammarSICXEParser.Inmediato3Context context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.subf2a"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubf2a([NotNull] GrammarSICXEParser.Subf2aContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.subf2b"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubf2b([NotNull] GrammarSICXEParser.Subf2bContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.subf2c"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubf2c([NotNull] GrammarSICXEParser.Subf2cContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.subf2d"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubf2d([NotNull] GrammarSICXEParser.Subf2dContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.codop1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCodop1([NotNull] GrammarSICXEParser.Codop1Context context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.codop2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCodop2([NotNull] GrammarSICXEParser.Codop2Context context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.codop3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCodop3([NotNull] GrammarSICXEParser.Codop3Context context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.reg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReg([NotNull] GrammarSICXEParser.RegContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpresion([NotNull] GrammarSICXEParser.ExpresionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.multiplicacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicacion([NotNull] GrammarSICXEParser.MultiplicacionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarSICXEParser.numero"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumero([NotNull] GrammarSICXEParser.NumeroContext context);
}
} // namespace Example.Generated
